project:
  type: website
  output-dir: docs

website:
  title: "Michael J. Moody"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: talks.qmd
        text: Talks
      - href: notes.qmd
        text: Notes
      - href: miscellaneous.qmd
        text: Misc

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: article
